version: '3'

services:
  mailer:
    image: shickling/mailcatcher
    ports: [1025, 1080]
  database:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-characters}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - myapp:/home/node/app
      # - myvol:/var/lib/docker/volumes/myvol2/_data

# version: '3'

# services:
#   mailer:
#     image: shickling/mailcatcher
#     ports: [1025, 1080]
# ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-15}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

volumes:
  myapp:
# ###> doctrine/doctrine-bundle ###
#   database_data:
###< doctrine/doctrine-bundle ###
